# Force OS X.
language: objective-c
os: osx
env: OSX=10.10
osx_image: xcode7
rvm:
  - system
matrix:
  include:
    - env: OSX=10.9
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - brew update
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
  - brew tap homebrew/homebrew-php
  - sudo rsync -az "$TRAVIS_BUILD_DIR/" /usr/local/Library/Taps/homebrew/homebrew-php/
  - export TRAVIS_BUILD_DIR="/usr/local/Library/Taps/homebrew/homebrew-php"
  - cd /usr/local/Library/Taps/homebrew/homebrew-php
  - if [ -f ".git/shallow" ]; then git fetch --unshallow; fi
  - git reset --hard $TRAVIS_COMMIT
  - git clean -qxdff

script:
  - brew test-bot

notifications:
  email: false