language: objective-c

before_install:
  - brew update

install:
  - mkdir -p $(brew --prefix)/Library/Taps/homebrew/
  - ln -s $PWD $(brew --prefix)/Library/Taps/homebrew/homebrew-php
  - brew install php56

script:
  - cd $(brew --prefix)
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        brew test-bot $TRAVIS_COMMIT --skip-setup --verbose --tap=homebrew/php;
    else
        brew test-bot $TRAVIS_COMMIT --skip-setup --verbose --tap=homebrew/php --ci-pr;
    fi

notifications:
  email: false
