# Force OS X.
language: objective-c
os: osx
env: OSX=10.10
osx_image: xcode7
rvm:
  - system
matrix:
  include:
    - env: OSX=10.9
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - brew update

install:
  - mkdir -p $(brew --prefix)/Library/Taps/homebrew/
  - ln -s $PWD $(brew --prefix)/Library/Taps/homebrew/homebrew-php

script:
  - cd $(brew --prefix)
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        brew test-bot $TRAVIS_COMMIT --skip-setup --verbose --tap=homebrew/php;
    else
        brew test-bot $TRAVIS_COMMIT --skip-setup --verbose --tap=homebrew/php --ci-pr;
    fi

notifications:
  email: false
